src/Entity/Registry.php
<?php

namespace App\Entity;

use App\Repository\RegistryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RegistryRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Registry
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="registries")
     */
    private $id_user;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="time")
     */
    private $entry_time;

    /**
     * @ORM\Column(type="time")
     */
    private $exit_time;

    /**
     * @ORM\Column(type="time")
     */
    private $delay_time;

    /**
     * @ORM\Column(type="time")
     */
    private $total_time;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getEntryTime(): ?\DateTimeInterface
    {
        return $this->entry_time;
    }

    public function setEntryTime(\DateTimeInterface $entry_time): self
    {
        $this->entry_time = $entry_time;

        return $this;
    }

    public function getExitTime(): ?\DateTimeInterface
    {
        return $this->exit_time;
    }

    public function setExitTime(\DateTimeInterface $exit_time): self
    {
        $this->exit_time = $exit_time;

        return $this;
    }

    public function getDelayTime(): ?\DateTimeInterface
    {
        return $this->delay_time;
    }

    public function setDelayTime(\DateTimeInterface $delay_time): self
    {
        $this->delay_time = $delay_time;

        return $this;
    }

    public function getTotalTime(): ?\DateTimeInterface
    {
        return $this->total_time;
    }

    public function setTotalTime(\DateTimeInterface $total_time): self
    {
        $this->total_time = $total_time;

        return $this;
    }
}

templates/pdf/registries-today.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Titre de la page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

</head>
<body>
<div class="alert alert-light" role="alert">
    <h1 class="alert-heading">
        <i class="bi bi-calendar-check"></i>
        {{ 'All the entries'|trans }}<br>
        {{ 'now'|date() }}
    </h1>
</div>

{% if registries %}
    <div class="alert alert-light" role="alert">
        <h4 class="alert-heading"><i class="bi bi-list-check"></i> {{ 'All the entries'|trans }}</h4>
        <p>{{ 'All the entries'|trans }}</p>
        <hr>

        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">{{ 'User'|trans }}</th>
                <th scope="col">{{ 'Date'|trans }}</th>
                <th scope="col">{{ 'Entry'|trans }}</th>
                <th scope="col">{{ 'Exit'|trans }}</th>
                <th scope="col">{{ 'Delay'|trans }}</th>
                <th scope="col">{{ 'Total'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for registry in registries %}
                {% if app.user.id == registry.idUser.id %}
                    <tr class="text-primary" style="vertical-align: middle;">
                {% else %}
                    <tr style="vertical-align: middle;">
                {% endif %}
                <td>
                    {% if app.user.role == 'ROLE_ADMIN' %}
                        <a href="{{ path('detail-user', { 'id': registry.idUser.id }) }}">
                            {{ registry.idUser.name }}
                        </a>
                    {% else %}
                        {{ registry.idUser.name }}
                    {% endif %}
                </td>
                <td>{{ registry.date|date("F jS") }}</td>
                <td>{{ registry.entryTime|date("H:i:s") }}</td>
                <td>
                    {% if registry.entryTime == registry.exitTime %}
                        -
                    {% else %}
                        {{ registry.exitTime|date("H:i:s") }}
                    {% endif %}
                </td>
                <td>{{ registry.delayTime|date("H:i:s") }}</td>
                <td>{{ registry.totalTime|date("H:i:s") }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <div class="alert alert-light" role="alert">
        <h4 class="alert-heading"><i class="bi bi-list-check"></i> {{ 'There\'s no registries yet'|trans }}</h4>
    </div>
{% endif %}

</body>
</html>