src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

// VALIDATE FORMS IN THIS CLASS
use Symfony\Component\Validator\Constraints as Assert;

// GET ENTRIES
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */

class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/[a-zA-Z]+/",
     *     message="Name should be written with letters"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/[a-zA-Z]+/",
     *     message="Last name should be written with letters"
     * )
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Email(
     *     message="email should be written; {{ value }} it's not valide",
     * )
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity=Registry::class, mappedBy="id_user", cascade={"remove"})
     * @ORM\OrderBy({"date"                         = "DESC"})
     */
    private $registries;

    /**
     * @ORM\OneToMany(targetEntity=Schedule::class, mappedBy="id_user", cascade={"remove"})
     */
    private $schedules;

    public function __construct()
    {
        $this->registries = new ArrayCollection();
        $this->schedules = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id)
    {
        $this->id = $id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Registry[]
     */
    public function getRegistries(): Collection
    {
        return $this->registries;
    }

    public function addRegistry(Registry $registry): self
    {
        if (!$this->registries->contains($registry)) {
            $this->registries[] = $registry;
            $registry->setIdUser($this);
        }

        return $this;
    }

    public function removeRegistry(Registry $registry): self
    {
        if ($this->registries->removeElement($registry)) {
            // set the owning side to null (unless already changed)
            if ($registry->getIdUser() === $this) {
                $registry->setIdUser(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        return array($this->getRole());
    }

    public function getSalt()
    {
        return null;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Schedule[]
     */
    public function getSchedules(): Collection
    {
        return $this->schedules;
    }

    public function addSchedule(Schedule $schedule): self
    {
        if (!$this->schedules->contains($schedule)) {
            $this->schedules[] = $schedule;
            $schedule->setIdUser($this);
        }

        return $this;
    }

    public function removeSchedule(Schedule $schedule): self
    {
        if ($this->schedules->removeElement($schedule)) {
            // set the owning side to null (unless already changed)
            if ($schedule->getIdUser() === $this) {
                $schedule->setIdUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

// FORM CREATION
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->setMethod('POST')
            ->add(
                'name', TextType::class, array(
                    'label' => 'Your Name',
                    'attr'  => ['class' => 'form-control']
                )
            )
            ->add(
                'last_name', TextType::class, array(
                    'label' => 'Your Last Name',
                    'attr'  => ['class' => 'form-control']
                )
            )
            ->add(
                'email', EmailType::class, array(
                    'label' => 'Your Email',
                    'attr'  => ['class' => 'form-control']
                )
            )
            ->add(
                'password', PasswordType::class, array(
                    'label' => 'Your Password',
                    'attr'  => ['class' => 'form-control']
                )
            )
            ->add(
                'submit', SubmitType::class, array(
                    'label' => 'Join us',
                    'attr'  => ['class' => 'btn btn-secondary btn-lg btn-block']
                )
            );
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Service\ScheduleService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;

// USE ENTITY
use App\Entity\User;

// USE CUSTOM FORMS
use App\Form\UserType;
use App\Form\LoginType;

// USE AUTHENTIC FOR LOGIN
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

// USE SERVICES
use App\Service\UserService;
use App\Service\RegistryService;

use Symfony\Component\Security\Core\Security;

class UserController extends AbstractController
{
    private $userService;
    private $registryService;
    private $security;

    public function __construct(
        UserService         $userService,
        RegistryService     $registryService,
        Security            $security
    ) {
        $this->registryService  = $registryService;
        $this->userService      = $userService;
        $this->security         = $security;
    }

    #[Route('/', name: 'home')]
    public function index(): Response
    {
        if ($this->security->getUser() && $this->security->getUser()->getRoles()[0] == 'ROLE_ADMIN') {
            return $this->redirectToRoute('admin');
        }

        $registries = $this->registryService->getRegistriesToday();

        return $this->render(
            'user/index.html.twig', [
            'registries' => $registries
            ]
        );
    }

    #[Route('/sign-up', name: 'sign-up')]
    public function create(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->userService->create($user);

            $session = new Session();
            $session->getFlashBag()->add('message', 'User created!');

            return $this->redirectToRoute('login');
        }

        $title = 'Time to be part of something great';

        return $this->render(
            'user/sign-up.html.twig', [
            'title' => $title,
            'form'  => $form->createView(),
            'user'  => $user
            ]
        );
    }

    #[Route('/user/{id}', name: 'detail-user')]
    public function read(User $user): Response
    {
        if ($this->security->getUser()->getRoles()[0] != 'ROLE_ADMIN' && $user != $this->security->getUser()) {
            return $this->redirectToRoute('home');
        }

        return $this->render(
            'user/detail.html.twig', [
            'user'          => $user,
            'schedules'     => $user->getSchedules(),
            'scheduleDay'   => false,
            'registries'    => $user->getRegistries()
            ]
        );
    }

    #[Route('/user/update/{id}', name: 'update-user')]
    public function update(Request $request, User $user): Response
    {

        if ($this->security->getUser()->getRoles()[0] != 'ROLE_ADMIN') {
            if ($this->security->getUser() != $user) {
                return $this->redirectToRoute('home');
            }
        }

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->userService->update($user)) {
                return $this->redirectToRoute('home');
            }
        }

        return $this->render(
            'user/sign-up.html.twig', [
            'title'     => 'Edit',
            'form'      => $form->createView()
            ]
        );
    }

    #[Route('/user/delete/{id}', name: 'delete-user')]
    public function delete(User $user): Response
    {
        if ($this->security->getUser()->getRoles()[0] == 'ROLE_ADMIN' || $user == $this->security->getUser()) {
            $this->userService->delete($user);
        }

        return $this->redirectToRoute('home');
    }

    // LOGIN
    #[Route('/login', name: 'login')]
    public function login(Request $request, AuthenticationUtils $authenticationUtils): Response
    {
        $user = new User();
        $form = $this->createForm(LoginType::class, $user);

        // FILL OBJECT WITH FORM DATA
        $form->handleRequest($request);

        $error          = $authenticationUtils->getLastAuthenticationError();
        $lastUserName   = $authenticationUtils->getLastUsername();

        return $this->render(
            'user/login.html.twig', array(
            'title'         => 'Log in',
            'error'         => $error,
            'form'          => $form->createView(),
            'last_username' => $lastUserName
            )
        );
    }
}

templates/user/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Details for {{ user.name }}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="jumbotron">
                <h1 class="display-4">{{ 'Details for'|trans }} {{ user.name }}</h1>
                <p class="lead" style="color: #eee; text-shadow: 1px 1px 1px #222;">
                    {{ 'Welcome'|trans }}
                </p>
                <hr class="my-4">
            </div>
        </div>
        <br>
        <div class="col-xs-12 col-md-4">
            <div class="alert alert-light" role="alert">
                <h4 class="alert-heading"><i class="bi bi-person"></i> {{ 'Profile'|trans }}</h4>
                <p><i class="bi bi-info-circle"></i> {{ user.name }}</p>
                <hr>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ 'Name'|trans }}: {{ user.name }}</li>
                    <li class="list-group-item">{{ 'Last name'|trans }}: {{ user.lastName }}</li>
                    <li class="list-group-item">{{ 'Registries'|trans }}: {{ user.getRegistries()|length }}</li>
                </ul>
                <div class="card-body">
                    <a href="{{ path('detail-user', { 'id': user.id }) }}" class="btn btn-light text-primary"><i class="bi bi-eye"></i></a>
                    <a href="{{ path('update-user', { 'id': user.id }) }}" class="btn btn-light text-warning"><i class="bi bi-pencil-square"></i></a>

                    <!-- MODAL ACTION -->
                    <a href="#"
                       type="button"
                       data-toggle="modal"
                       data-target="#modalErase{{ user.id }}"
                       class="btn btn-light text-danger">
                        <i class="bi bi-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div id="modalErase{{ user.id }}" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content alert alert-danger">
                                <div class="modal-header">
                                    <h4 class="modal-title"><i class="bi bi-chat-left"></i> Message</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="alert alert-danger border font-weight-bold" role="alert">
                                        {{ 'Do you want remove  ' ~ user.name ~ '?'|trans }}<br>
                                        <a href="{{ path('delete-user', { 'id': user.id }) }}">{{ 'Yes, i want to'|trans }}</a>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-8">
            <div class="alert alert-light" role="alert">
                <h4 class="alert-heading"><i class="bi bi-calendar-date"></i> {{ 'Schedule'|trans }}</h4>
                <p>{{ 'Schedule'|trans }}</p>
                <hr>
                {{ include('Include/schedule.html.twig') }}
            </div>
            {{ include('Include/registries-list.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if app.user %}
        Hello {{ app.user.name }}
    {% else %}
        Badgeuse!
    {% endif %}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="col-12">
                <div class="jumbotron">
                    <h1 class="display-4">
                        {% if app.user %}
                            {{ 'Home'|trans }}
                        {% else %}
                            {{ 'Welcome'|trans }}
                        {% endif %}
                    </h1>
                    <p class="lead" style="color: #eee; text-shadow: 1px 1px 1px #222;">
                        {{ 'Welcome'|trans }}
                    </p>
                    <hr class="my-4">
                </div>
            </div>
            <br>

        {% if app.user %}
        <div class="row">
            <div class="col-xs-12 col-md-4">
                <div class="alert alert-light" role="alert">
                    <h4 class="alert-heading">
                        <i class="bi bi-calendar-check"></i>
                        {{ 'Actions'|trans }}
                    </h4>
                    <hr class="my-4">
                    <a href="{{ path('upregistry', { 'id': app.user.id }) }}" class="col-12 btn btn-secondary text-light">
                        {{ 'Enter'|trans }} <i class="bi bi-box-arrow-in-right"></i>
                    </a>
                    <br>
                    <br>
                    <a href="{{ path('downregistry', { 'id': app.user.id }) }}" class="col-12 btn btn-dark text-light">
                        {{ 'Exit'|trans }} <i class="bi bi-box-arrow-right"></i>
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-md-8">
                <div class="alert alert-light" role="alert">
                    <h4 class="alert-heading">
                        <i class="bi bi-calendar-check"></i>
                        {{ 'All the entries'|trans }}<br>
                        {{ 'now'|date() }}
                    </h4>
                </div>
                    {{ include('Include/registries-list.html.twig') }}
            </div>
        </div>
        {% else %}
            <h2>You can start now</h2>
        {% endif %}
        </div>
    </div>


{% endblock %}

templates/user/login.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title|trans }} {% endblock %}

{% block body %}
    <div class="example-wrapper">
            <div class="row">
                <div class="col-6" style="color:#eee; text-shadow: 1px 1px 5px #222;">
                    <h1>{{ title|trans }}</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis sapien sit amet
                        Cras ut tincidunt erat. Nunc sed erat imperdiet, finibus lacus ut, mollis nisi. Etiam venenatis
                        felis a varius imperdiet. Integer faucibus rhoncus ornare. Sed a rhoncus metus, quis pulvinar
                        eros.
                    </p>
                </div>
                <div class="col-6">
                    {{ form_start(form) }}
                    {{ form_row(form.email, {'full_name':'_username', 'value':last_username }) }}
                    {{ form_row(form.password, {'full_name':'_password'}) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                    {% if error %}
                        <br>
                        <div class="alert alert-danger">
                            {{ error.messagekey|trans(error.messageData, 'security') }}
                        </div>
                    {% endif %}
                    {% for message in app.session.flashbag().get('message') %}
                        <br>
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
    </div>
{% endblock %}

templates/user/sign-up.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <div class="example-wrapper">

            <div class="row">
                <div class="col-6" style="color:#eee; text-shadow: 1px 1px 5px #222;">
                    <h1>{{ title|trans }}</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis sapien sit amet
                        Cras ut tincidunt erat. Nunc sed erat imperdiet, finibus lacus ut, mollis nisi. Etiam venenatis
                        felis a varius imperdiet. Integer faucibus rhoncus ornare. Sed a rhoncus metus, quis pulvinar
                        eros.
                    </p>
                </div>
                <div class="col-6">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}

                    {% for message in app.session.flashbag().get('message') %}
                        <br>
                        <div class="alert alert-danger">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>


    </div>
{% endblock %}

templates/user/users.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="jumbotron">
                <h1 class="display-4">{{ 'All the users'|trans }}</h1>
                <p class="lead" style="color: #eee; text-shadow: 1px 1px 1px #222;">
                    {{ 'You have total control right here'|trans }}
                </p>
                <hr class="my-4">
            </div>
        </div>
    {% for user in users %}
    <div class="col-3 card" style="border: solid 10px #ccc;">
        <div class="card-body">
            <h3>{{ user.name ~ ' ' ~ user.lastName}}</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ 'Name'|trans }}: {{ user.name }}</li>
                <li class="list-group-item">{{ 'Last name'|trans }}: {{ user.lastName }}</li>
                <li class="list-group-item">{{ 'Registries'|trans }}: {{ user.getRegistries()|length }}</li>
                <div style="text-align: center;">
                    <a href="{{ path('detail-user', { 'id': user.id }) }}" class="btn btn-light text-primary"><i class="bi bi-eye"></i></a>
                    <a href="{{ path('update-user', { 'id': user.id }) }}" class="btn btn-light text-warning"><i class="bi bi-pencil-square"></i></a>

                    <!-- MODAL ACTION -->
                    <a href="#"
                       type="button"
                       data-toggle="modal"
                       data-target="#modalErase{{ user.id }}"
                       class="btn btn-light text-danger">
                        <i class="bi bi-trash"></i>
                    </a>

                    <!-- Modal -->
                    <div id="modalErase{{ user.id }}" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content alert alert-danger">
                                <div class="modal-header">
                                    <h4 class="modal-title"><i class="bi bi-chat-left"></i> Message</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="alert alert-danger border font-weight-bold" role="alert">
                                        {{ 'Do you want remove  ' ~ user.name ~ '?'|trans }}<br>
                                        <a href="{{ path('delete-user', { 'id': user.id }) }}">{{ 'Yes, i want to'|trans }}</a>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </ul>
        </div>
    </div>
    {% endfor %}
    </div>
{% endblock %}